version: '3.8'
services:
  db:                     
    image: mysql:latest  
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manish123
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: manish123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uadmin", "-pmanish123"]
    deploy:
      resources:
        limits:
          memory: 400M 
    command: --innodb-buffer-pool-size=64M
    
volumes:
  mysql_data:            
